#!/bin/bash

DBEAVER_VERSION="7.2.5"

exec bash -c "
docker run --rm \
    --network host \
    -v ~/.dbeaver/DBeaverData:/root/.local/share/DBeaverData \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
    -e GTK_THEME=Adwaita:dark \
    seudev/dbeaver:$DBEAVER_VERSION
"
